### ISSUE TITLE
Moiré patterns

### ISSUE THREAD

**Issue by aivrar** [aivrar/360r#13]
@awoodfinz mentioned there was a moiré pattern on one of the couches? Which one, will you render again or fix in ps?

**Comment by awoodfinz** [comment]
i will try ps 1st

**Comment by awoodfinz** [comment]
I use this technique to remove it https://www.youtube.com/watch?v=keG8IGndm_M

Updated assets in this folder https://www.dropbox.com/sh/houlczgrbfuowq8/AAByZkr997L8wBwGPKHL4Qoha?dl=0

**Comment by aivrar** [comment]
very cool
