### ISSUE TITLE
Paint selection book

### ISSUE THREAD

**Issue by aivrar** [aivrar/360r#15]
Can we cut it out better in photoshop, align the fonts up better and remove some duplicate buttons
> no small play button  delete the one in the hexagon) 
> Make the close button smaller and not in a hexagon 
> Remove the words next page
> Cut edges of book up better
> Remove random printing on folder 'next page' part
> No use of italic fonts
> Use fonts from these sets https://github.com/AppleDesignResources/SanFranciscoFont
![image](https://cloud.githubusercontent.com/assets/15573580/19847477/6d2cbd7c-9f04-11e6-89ca-adb6cbdec2c7.png)

**Comment by netneko21** [comment]
no small play button - play button change pages of current palette. 
close button - ok
Remove the words next page - ok 
Cut edges of book up better - waiting for new image 
No use of italic fonts - ok
Use fonts from these sets - ok

**Comment by netneko21** [comment]
conflict with #8
