### ISSUE TITLE
New white renders

### ISSUE THREAD

**Issue by awoodfinz** [aivrar/360r#20]
Please see attached sample to see if this is appropriate for our current colouring system

The differences is i set up walls are white instead of grey in the hope that this will lead to better colour accuracy 
![living_room_master_v02](https://cloud.githubusercontent.com/assets/20102290/19986423/86902b94-a27b-11e6-864d-8b68864ba491.jpg)

**Comment by awoodfinz** [comment]
Assets for new white renders are here

https://www.dropbox.com/sh/houlczgrbfuowq8/AAByZkr997L8wBwGPKHL4Qoha?dl=0

**Comment by netneko21** [comment]
done. white renders for living room.  v19.
